### ISSUE TITLE
Why isn't parse_url a constructor?

### ISSUE THREAD

**Issue by lemire** [ada-url/ada#151] opened 2023-01-28 16:17 UTC
The `parse_url` function returns a URL. In many URL parsing library, there is no `parse_url` and you just do...

```
ada::url url("http://google.com")
```

or the equivalent.

Now, having a `parsing` function could make sense *if* you have a parser. So you do...

```
ada::parser p;
ada::url = p.parse("http://google.com");
```

This can make sense because the parser instance can hold some ressources (such as space for temporary buffers) and it can also hold configuration switches.

**Comment by anonrig** [comment] 2023-02-02 20:23
I recommend resolving this issue before our initial release.

**Comment by lemire** [comment] 2023-02-03 01:27
The problem with the current design is that people will do...
```C++
ada::url u = parse("http://bad url :100000")
std::cout << url.get_href() << std::endl;
```
And then they will get a bad result.

A constructor is not much better... 

```C++
ada::url u("http://bad url :100000")
std::cout << url.get_href() << std::endl;
```

Unless, of course, you throw on error, but so far we have not used exceptions very much.

We could throw. It is sensible. Then people would need to do the try and catch dance. It feels like people are a bit tired of that, however.


Another API would be...

```
url u; // always success;
bool valid = u.parse("http://bad url :100000");
if(! u.parse("http://bad url :100000")) {
// it is a bad URL
}
```

We can require that people are force to process the boolean (is_valid).

Well. If we do that, we have to make sure that when the parse function fails, we clear the url instance, so that you can safely do...

```C++
url u; // always success;
bool valid = u.parse("http://bad url :100000");
if(! u.parse("http://bad url :100000")) {
puts("bad url");
}
if(! u.parse("http://google.com")) {
// will not get here
}
// here u is proper despite the failure above.
```

Well ok. But then suppose you want to do...

```C++
void f(ada::url u) {...}

...

f(parse("http://google.com")); // pass the parsed url to f
```

You can't anymore.

In simdjson, we have a very clever system but we wanted to do something crazy called chaining....

```C++
object["key"]["other"].get_double()
```

So we pass a result instance from element to element. We don't need anything of the sort in ada.

What about 

https://en.cppreference.com/w/cpp/header/expected

It is not available in the runtime yet, but we can use a library right now...

https://github.com/TartanLlama/expected

This would mean that we could actually remove the is_valid field from the struct entirely. Instead, we could report a descriptive error. I mean... we know why we are failing most times? Or, at least, we know at which state we failed... so we know we failed to parse the scheme and so forth. So we could report a failure code... 

I have never used it before, but std::expected as to work with relative fat structure like ours... so it can't entice users to make copies and so forth. Plus, once C++23 becomes mainstream, in many years, we are standard.

One potential concern is bloat. The expected.hpp file is 90 kB. So adding it to the project would add over 50% to our code size, and potentially some to our binary size. I personally don't care much about that but some people have complained that simdutf.o compiles to a binary over over 100 kB. 

cc @TartanLlama

**Comment by lemire** [comment] 2023-02-03 01:42
@anonrig The whatwg standard seems to require a constructor. I find this strange. I don't understand why a team standardizing the URL format would prescribe the API.

**Comment by anonrig** [comment] 2023-02-03 01:50
I'm more positive about `ada::url u = ada::url("/hello", "https://google.com");`

whatwg standard focuses on API primarily to make sure that all browsers implement the same API surface layer. Since we're a library, I don't think we should conform to API description of the whatwg standard...

**Comment by lemire** [comment] 2023-02-03 16:19
I don't think ...

`ada::url u = ada::url("/hello", "https://google.com");`

is right... You mean?

`ada::url u("/hello", "https://google.com");`

That's fine but you have to explain what happens in case of an error. My point above is that if you expect users to carefully check `u.is_valid`... Well, that's not going to happen... people will do...

`ada::url u("https://[bad url]", "https://google.com"); std::cout << u.get_host() << std::end;`

and they will complain if they don't get what they want.

Now, if we want to do that for the first release, that's fine. But then we should update the README and be explicit. Right now, we propose people do...

```
ada::url url = ada::parse(....);
url.set_protocol(...);
```

Where is the error handling?

```C++
ada::url url = ada::parse(....);
if(url.is_valid) { 
url.set_protocol(...);
// how to check for an error here?
}
```

Error handling is very important because people *will* get it wrong and they will blame the library.

**Comment by anonrig** [comment] 2023-02-03 16:40
What about?

```
ada::parse_result result = ada::parse(...);

if (result.is_valid) {
  std::optional<ada::url> = result.get_url();
}

```

I see that we have a couple of options:
- Give the responsibility to the user to check whether url is valid before accessing getters
- Create an illusion with the abstraction (and may be with std::optional) to force developers to check
- Throw error (who wants that?)
- Make all getters nullable if the parse result is invalid. (I'm kind of `meh` in this)

Setters are a different scenario except for invalid inputs on `url.set_href()`. You should not throw an error for any other setter function and omit the result. (This is the behavior of web browsers and runtimes implementing WHATWG URL, and we don't have to conform to this, since we'll never be used by end-users but only be implemented by the developers of those tools)

For example: `new URL('http://google.com').href = '#'` throws an error, but `new URL('http://google.com').protocol = '#'` does not throw an error. (And this is the intended behavior according to WHATWG spec)

**Comment by lemire** [comment] 2023-02-03 17:02
Regarding...

```C++
ada::parse_result result = ada::parse(...);

if (result.is_valid) {
  std::optional<ada::url> = result.get_url();
}
```

You may have noticed that in our benchmarks, I included two versions of how one might use Ada, one where copies are made, and one where no copy is made. You may have noticed that there is a very measurable performance difference.

This latest proposal is likely to trigger a whole lot of copying and it will adversely affect performance.

**Comment by lemire** [comment] 2023-02-03 21:00
Note that std::expected will become standard in C++23.

**Comment by anonrig** [comment] 2023-02-03 21:07
Note: Node.js still does not support C++20, and it might take couple of months before supporting it. I don't think it would be an ideal scenario (at least for a year or two) for Node to use C++23.

**Closed** 2023-02-03 21:14 UTC
Labels: good first issue

**Comment by lemire** [comment] 2023-02-03 22:57
> Note: Node.js still does not support C++20, and it might take couple of months before supporting it. I don't think it would be an ideal scenario (at least for a year or two) for Node to use C++23.

Nobody supports C++23. We do it through a temporary add-on implementation that only requires C++11.
